Class {
	#name : #MLSAnalysisMethodSample,
	#superclass : #Object,
	#instVars : [
		'methods',
		'name'
	],
	#category : #'MagicLiteralsSelector-analysis'
}

{ #category : #accessing }
MLSAnalysisMethodSample >> methods [
	^ methods
]

{ #category : #accessing }
MLSAnalysisMethodSample >> methods: anObject [
	methods := anObject
]

{ #category : #accessing }
MLSAnalysisMethodSample >> name [
	^ name
]

{ #category : #accessing }
MLSAnalysisMethodSample >> name: anObject [
	name := anObject
]
